DELETE http://localhost:3001/api/persons/665da4a24b53dbf1e38fbc64

###

GET http://localhost:3001/api/persons

###

POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "Akash Sharma",
    "number": 9625703834
}

###

PUT http://localhost:3001/api/persons/665dc9e63878dbc7c3440783
content-type: application/json

{
    "name": "Akash Sharma",
    "number": 96885031888823
}

###

GET http://localhost:3001/api/persons/665da4a24b53dbf1e38fbc64