DELETE http://localhost:3000/api/persons/8541

###

GET http://localhost:3001/api/persons

###

POST http://localhost:3000/api/persons
content-type: application/json

{
    "name": "Akash Sharma",
    "number": "9625703834"
}